{"uuid": "afa61aba-86da-405c-a37b-a4421663466f", "children": ["9e516b20-6859-4651-b6a4-2bfe12b83b8a"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages\n\n", "trace": "  File \"d:\\onedrive - cactus\\python\\sel_python\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\onedrive - cactus\\python\\sel_python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\onedrive - cactus\\python\\sel_python\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\OneDrive - CACTUS\\Python\\Sel_python\\Pytest\\Test_GDPR_Verification.py\", line 19, in test_setup\n    self.driver = webdriver.Chrome(executable_path=\n  File \"d:\\onedrive - cactus\\python\\sel_python\\venv\\lib\\site-packages\\seleniumwire\\webdriver.py\", line 115, in __init__\n    super().__init__(*args, **kwargs)\n  File \"C:\\Program Files (x86)\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Program Files (x86)\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Program Files (x86)\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Program Files (x86)\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Program Files (x86)\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1627216367004, "stop": 1627216429670}], "start": 1627216367004, "stop": 1627216429764}